// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX963ccHXZio1sf87viuRpAoumIjdNLe8',
    appId: '1:864118670985:web:b135c6c8e7460c0bc4e858',
    messagingSenderId: '864118670985',
    projectId: 'fir-new-1464b',
    authDomain: 'fir-new-1464b.firebaseapp.com',
    storageBucket: 'fir-new-1464b.firebasestorage.app',
    measurementId: 'G-CHJXNJ46J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjehtvDcvo_KlA1CI7q3m67NnwiUXcoYA',
    appId: '1:864118670985:android:33913ea85ebbe7eac4e858',
    messagingSenderId: '864118670985',
    projectId: 'fir-new-1464b',
    storageBucket: 'fir-new-1464b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5shOJG5iu_ic3NweRuOVyMmgLaU4cj9c',
    appId: '1:864118670985:ios:f9f14be16fdfdebec4e858',
    messagingSenderId: '864118670985',
    projectId: 'fir-new-1464b',
    storageBucket: 'fir-new-1464b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5shOJG5iu_ic3NweRuOVyMmgLaU4cj9c',
    appId: '1:864118670985:ios:f9f14be16fdfdebec4e858',
    messagingSenderId: '864118670985',
    projectId: 'fir-new-1464b',
    storageBucket: 'fir-new-1464b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX963ccHXZio1sf87viuRpAoumIjdNLe8',
    appId: '1:864118670985:web:265b2eaa9f6a641bc4e858',
    messagingSenderId: '864118670985',
    projectId: 'fir-new-1464b',
    authDomain: 'fir-new-1464b.firebaseapp.com',
    storageBucket: 'fir-new-1464b.firebasestorage.app',
    measurementId: 'G-3E3H7922GR',
  );
}
